#! /usr/bin/env bash

# Generate HTML files from markdown ones
# Argument gives specific files if present; otherwise convert everything
for f in ${1-*.md */*.md} ${@:2:$#}
do
  ./dzref md.bqn "ConvertFile \"$f\""
done
