# Strings, comments, whitespace
# Can't test LF inside quotes here
"#"≡⥊'#'
0 % ≠""#""
1#+1\#'
1 #,0⋄0
1     #"␖ 
	1
(@+9)≡'	'  #tab	

# Juxtaposition
@‿π ≡ ≍⟜π@
·2⊸≡2
6 % 33-⋆⟜3 3
⊑=⟜'a'"a"
F←-○≠ ⋄ "abcd"F"bcd"

# Special names
9 % 1⊸+{𝕗𝕗∘{𝕎𝕩}⍟𝕩𝕩}3
0+{𝕎𝕏𝔽𝔾𝕊⋄1}-2
! % {_𝕩}4
! % 0{2_𝕣⋄𝕩} 1
! % 0{_𝕣_𝕣_⋄𝕩} 1
! % {_𝕣a_}
! % {𝕣_}
! % {_𝕣__}
! % {•_𝕣}
! % {a𝕣r}
! % 0{1{𝕘⋄𝕗}𝕣𝕣⋄𝕩} 1

# Variable names
3 % a←3 ⋄ _A_
under←π ⋄ uNdER_ ≡ u_n__d___e____r
_f←{-𝕗} ⋄ ¯1 __f

# Non-allowed characters (last is vertical tab)
! % *
! % ^
! % 
